User
RSS-React-2022Q3-Team-27/project-management-app pull request #6
Opened 2022-11-10 23:07 UTC by LilithPrimary

#### 🤔 This is a ...

- [+] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related trello card link

[task](https://trello.com/c/5iUMzqqI/13-registration-authorization)

#### 💡 Background and solution

Add Sign Up, Sign In requests and fields. Get user Id request

2022-11-10 23:50 UTC, oxanacode approved these changes, later dismissed

2022-11-10 23:55 UTC, Bumble-sakh requested changes

2022-11-10 23:55 UTC, Bumble-sakh commented on src/pages/SignIn/SignIn.tsx
> +      console.log(id);
Давайте убирать консоль.логи. за них есть штрафы.

2022-11-10 23:55 UTC, Bumble-sakh commented on src/store/slices/user/userThunks.ts
> +});
мб вынести в отдельный слайс?
нам ведь список юзеров не только при регистрации будет нужен.

в таск можно юзеров добавлять, для этого нужен список.

2022-11-10 23:55 UTC, Bumble-sakh commented on src/pages/SignUp/SignUp.tsx
> +  return (
а зачем редирект на sign-in после регистрации?
не лучше сделать автологин?

а если регистрация не пройдет, все равно редиректнет?

2022-11-10 23:57 UTC, Bumble-sakh commented
И общее, что б не забыть:
У нас появляется много текста в коде. Надо начать перевод.
Сегодня обсудим.

2022-11-11 00:06 UTC, LilithPrimary commented on src/pages/SignUp/SignUp.tsx
> +  return (
Ещё не писала для ошибок ничего, это так, на пробу можно сказать, могу удалить) Пока у нас должны быть исключительно удачные регистрации и авторизации)

2022-11-11 00:24 UTC, LilithPrimary commented on src/pages/SignIn/SignIn.tsx
> +      console.log(id);
Есть, сэр

2022-11-11 00:25 UTC, LilithPrimary commented on src/store/slices/user/userThunks.ts
> +});
Да, вынесем

2022-11-11 09:04 UTC, oxanacode approved these changes

2022-11-11 09:05 UTC, Bumble-sakh approved these changes

2022-11-11 09:05 UTC, merged